DROP TABLE IF EXISTS permits; CREATE TABLE permits (id TEXT PRIMARY KEY, address TEXT NOT NULL, status TEXT NOT NULL, hoa TEXT, days INTEGER NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
